name: Telegram Notification

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get last commit message for push
        if: github.event_name == 'push'
        id: get_commit_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
      - name: Get pull request title for PR
        if: github.event_name == 'pull_request'
        id: get_pr_title
        run: echo "::set-output name=message::${{ github.event.pull_request.title }}"

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: | 
            Event: ${{ github.event_name }}
            Repository: ${{ github.repository }}
            By: "${{ github.actor }}"
            Commit: ${{ github.sha }}
            Ref: ${{ github.ref }}
            Message: ${{ steps.get_commit_message.outputs.message || steps.get_pr_title.outputs.message }}
