name: Publish

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "20"

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Run Tests
  #       run: npm test

  # publish:
  #   name: Publish to npm
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "20"
  #         registry-url: "https://registry.npmjs.org"
  #     - name: Publish
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest # Ganti dengan jenis sistem operasi yang sesuai

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Ganti dengan versi Node.js yang sesuai

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.TOKEN_GITHUB}}" > ~/.npmrc

      - name: Install dependencies
        run: npm install # Atau ganti dengan perintah instalasi paket yang sesuai

      - name: Publish to GitHub Package Registry
        run: npm publish --access public --registry=https://npm.pkg.github.com/

  # create-release:
  #   name: Create Release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "20"

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  #       with:
  #         tag_name: v1.0.3 # Ganti dengan versi rilis yang sesuai
  #         release_name: Release v1.0.3
  #         body: |
  #           Deskripsi rilis Anda di sini.
  #         draft: false
  #         prerelease: false
  #     - name: Set Release ID
  #       run: echo "RELEASE_ID=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV

  # ghcr-publish:
  #   name: Publish to GitHub Container Registry
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@main

  #     - name: "Login to GitHub Container Registry"
  #       run: |
  #         echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     - name: "Build Inventory Image"
  #       run: |
  #         docker build . --tag ghcr.io/naandan/test:v1
  #         docker push ghcr.io/naandan/test:v1
